relax-not-relax/ThinkTank-mobile

lib/data/data.dart
lib/screens/option_home.dart
lib/widgets/others/contest_slider.dart

Update home screen UI

---

lib/screens/notification/notiscreen.dart

- Change the screen to StatefulWidget

Update Notification Screen

---

lib/screens/game/game_menu.dart

Update Game Menu Screen

---

lib/main.dart
lib/widgets/game/level_item.dart
lib/widgets/others/style_button.dart

Optimize code

---

lib/main.dart
lib/screens/flipcard/flipcard_game.dart

- Update game logic (fix bug when clicking more than 2 flip card at the same time)

Update Gameplay Flip Card Challenge

---

lib/api/achieviements_api.dart
lib/api/authentication_api.dart
lib/api/friends_api.dart
lib/main.dart
lib/models/friendship.dart
lib/screens/authentication/loginscreen.dart
lib/screens/friend/addfriend_screen.dart
lib/screens/friend/firend_screen.dart
lib/screens/game/game_menu.dart
lib/screens/home.dart
lib/screens/musicpassword/musicpassgame.dart
lib/widgets/game/level_item.dart

- Search my firend.
- Search friend.
- Add friend. Synchronized level of accout:
- Call API get Level.
- Save and Call when  play game.

Call API Friend:

---

lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/imagesWalkthrough/imageswalkthroughgame_screen.dart
lib/widgets/game/level_item.dart
lib/widgets/game/walkthrough_item.dart

- Update game logic for incorrect image choice

Update Images Walkthrough Gameplay

---

lib/screens/account/editaccount_screen.dart
linux/flutter/generated_plugin_registrant.cc
linux/flutter/generated_plugins.cmake
macos/Flutter/GeneratedPluginRegistrant.swift
pubspec.lock
pubspec.yaml
windows/flutter/generated_plugin_registrant.cc
windows/flutter/generated_plugins.cmake

Change Profile Picture

---

lib/api/account_api.dart
lib/api/authentication_api.dart
lib/models/account.dart
lib/models/password.dart
lib/screens/account/changepassword_screen.dart
lib/screens/account/editaccount_screen.dart
lib/screens/authentication/loginscreen.dart
lib/screens/friend/addfriend_screen.dart
lib/screens/friend/firend_screen.dart
lib/screens/friend/friend_request_screen.dart
lib/screens/musicpassword/musicpassgame.dart
lib/widgets/others/datetime_picker.dart
lib/widgets/others/editPass_field.dart
lib/widgets/others/editaccount_field.dart
lib/widgets/others/editaccountpass_field.dart
lib/widgets/others/selector_form.dart

- Connect API Account Management
- Change Account Model

Update Account Management Screen

---

lib/api/account_api.dart
lib/api/firebase_message_api.dart
lib/api/notification_api.dart
lib/data/data.dart
lib/helper/sharedpreferenceshelper.dart
lib/main.dart
lib/models/notification_item.dart
lib/screens/account/editaccount_screen.dart
lib/screens/authentication/loginscreen.dart
lib/screens/friend/friend_screen.dart
lib/screens/home.dart
lib/screens/notification/notiscreen.dart
lib/screens/option_home.dart
lib/screens/startscreen.dart
lib/widgets/appbar/appbar.dart
lib/widgets/others/noti_element.dart

- Connect API to handle Notification
- Handle push notifications in real time

Update Notification Management

---

lib/api/firebase_message_api.dart
lib/main.dart
lib/models/achievement.dart
lib/screens/achievement/challenges_screen.dart
lib/screens/findanonymous/cardprovider.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/screens/home.dart

- Update logic game play.
- Update UI Item Challenge.

Update Find Anonymous Game, Update UI Challenges Screen:

---

lib/api/assets_api.dart
lib/helper/sharedpreferenceshelper.dart
lib/main.dart
lib/models/findanounymous_assets.dart
lib/models/flipcard.dart
lib/screens/authentication/loginscreen.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/home.dart
lib/screens/startscreen.dart

- Create get resource function

Add GetResourceFunction:

---

lib/api/achieviements_api.dart
lib/models/game.dart
lib/screens/authentication/loginscreen.dart
lib/widgets/others/winscreen.dart

- loginscreen.dart
- achieviements_api.dart
- game.dart
- winscreen.dart

Update Files (Change variables name)

---

lib/api/assets_api.dart
lib/models/findanonymous.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/widgets/game/level_item.dart

Fix API getResource

---

lib/api/achieviements_api.dart
lib/api/assets_api.dart
lib/models/flipcard.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/game/game_menu.dart
lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/imagesWalkthrough/startgame_screen.dart
lib/screens/musicpassword/musicpassgame.dart
lib/screens/option_home.dart
lib/widgets/others/winscreen.dart

- Add mounted at setState
- Fix API get Level
- Fix get Time Flipcard game
- Call API Save Achivement

Fix getLevel of all games

---

lib/screens/flipcard/flipcard_game.dart

- Fix bug when clicking on 1 card 2 times continuously

Fix Flip Card Gameplay

---

lib/api/friends_api.dart
lib/api/notification_api.dart
lib/main.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/screens/friend/addfriend_screen.dart
lib/screens/friend/friend_request_screen.dart
lib/screens/friend/friend_screen.dart
lib/widgets/others/applifecycleobserver .dart
lib/widgets/others/winscreen.dart

- Add call refresh token at FriendAPI
- Add Turn off online status

Fix Friends Function

---

android/app/google-services.json
lib/api/authentication_api.dart
lib/screens/authentication/loginscreen.dart
lib/screens/startscreen.dart
pubspec.lock
pubspec.yaml

- Auto login if logined
- Login with Google

Update Save Login info, Google login

---

lib/screens/findanonymous/findanonymous_game.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/musicpassword/musicpassgame.dart

- Fix logical increase level of all game

Fix Logical Increase Level game

---

lib/api/authentication_api.dart
lib/helper/sharedpreferenceshelper.dart
lib/screens/account/account_mainscreen.dart

- Call API logout
- Set Loading when logout
- Remove date Shareprereference when logout

Add logout function:

---

lib/screens/account/editaccount_screen.dart

- Fix update account when logging in with Google

Update Edit Account Function

---

lib/api/account_api.dart
lib/api/challenges_api.dart

- Fix wrong token in API getChallenges

Fixbug API getChallanges

---

lib/main.dart
lib/screens/account/account_mainscreen.dart
lib/screens/account/editaccount_screen.dart
lib/screens/authentication/forgotpassscreen.dart
lib/screens/authentication/loginscreen.dart
lib/screens/authentication/registerscreen.dart
lib/screens/contest/contest_menu.dart
lib/screens/contest/finalresult_screen.dart
lib/screens/contest/instruction_screen.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/screens/friend/addfriend_screen.dart
lib/screens/friend/friend_request_screen.dart
lib/screens/friend/friend_screen.dart
lib/screens/notification/notiscreen.dart
lib/screens/startscreen.dart
lib/widgets/game/coin_div.dart
lib/widgets/others/loadingcustom.dart
lib/widgets/others/spinrer.dart
lib/widgets/others/style_button.dart
lib/widgets/others/winscreen.dart

- Instruction Screen
- Menu Screen
- Update Loading Spinner

Update Contest Screen

---

lib/models/imageswalkthrough_game.dart

- Fix auto increasing time function

Fix Images Walkthrough Gameplay

---

lib/main.dart
lib/screens/account/account_mainscreen.dart

- Show Confirmation dialog when clicking logout

Update Edit Account Main Screen

---

lib/api/achieviements_api.dart
lib/api/authentication_api.dart
lib/api/notification_api.dart
lib/models/accountinrank.dart
lib/screens/authentication/forgotpassscreen.dart
lib/screens/authentication/loginscreen.dart
lib/screens/game/game_menu.dart
lib/screens/game/leaderboard.dart
lib/widgets/game/leaderboard_user.dart
lib/widgets/game/top_user.dart

- Fix UI forgot password
- Call API forgotpassword
- Call API getLeaderboard

Done Leaderboard, Forgotpassword

---

lib/main.dart
lib/screens/flipcard/flipcard_game.dart
lib/widgets/game/level_item.dart

- Fix clicking 2 cards instantly

Update Flip Card Gamelplay

---

lib/main.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/game/leaderboard.dart
lib/widgets/game/level_item.dart
lib/widgets/game/top_user.dart

- Update UI, fixing size of elements

Update Leaderboard Screen

---

lib/main.dart
lib/screens/friend/addfriend_screen.dart
lib/screens/friend/friend_request_screen.dart
lib/screens/friend/friend_screen.dart
lib/screens/game/leaderboard.dart

- Fix UI with resizing elements

Update Friends Screen

---

lib/api/achieviements_api.dart
lib/api/challenges_api.dart
lib/screens/achievement/challenges_screen.dart
lib/screens/achievement/missioncomplete_screen.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/musicpassword/musicpassgame.dart

- Connect API Get badges
- Update api get challenges function

Update Achievement Screen

---

lib/api/assets_api.dart
lib/api/contest_api.dart
lib/data/data.dart
lib/helper/sharedpreferenceshelper.dart
lib/models/contest.dart
lib/models/imageswalkthrough_game.dart
lib/screens/authentication/loginscreen.dart
lib/screens/contest/contest_menu.dart
lib/screens/game/leaderboard.dart
lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/option_home.dart
lib/widgets/game/contest_thumbnail.dart
lib/widgets/game/level_item.dart

- Call API get Contest Resource
- Get Resource for ImageWalkthroug Contest

Update Contest Function

---

lib/api/assets_api.dart
lib/api/authentication_api.dart
lib/api/contest_api.dart
lib/models/musicpassword.dart
lib/screens/achievement/challenges_screen.dart
lib/screens/authentication/loginscreen.dart
lib/screens/contest/contest_menu.dart
lib/screens/musicpassword/musicpassgame.dart

- Call API get Assets Musicpassword
- Call API get Contest Musicpassword
- Display coin in Misson Screen
- Set pushAndRemoveUNtil when psuh screen Gameply contest

Update Musicpassword GamePLay

---

lib/screens/imagesWalkthrough/battle/game_mainscreen.dart

Update Game Battle Main Screen

---

lib/models/analysis.dart
lib/models/analysis_type.dart
lib/screens/analytics/memory_mainscreen.dart
lib/screens/analytics/statistics_screen.dart
lib/widgets/analyst/game_statistic_item.dart
lib/widgets/analyst/indicator.dart
lib/widgets/analyst/pie_chart_memory.dart

- Add and call Analyst API
- Create function of Memory trends function
- Create function to view by days and by weeks of memory tracking
- View Charts of Memory trends and statistics for each game

Create Chart Screen

---

lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/widgets/appbar/battle_game_appbar.dart

- Add competitor processing bar

Update 1v1 Appbar

---

lib/models/account.dart
lib/screens/contest/finalresult_screen.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/game/battle_main_screen.dart
lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/musicpassword/musicpassgame.dart

- Add win Screen for all game contest

Add WinScreen contest

---

lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/screens/imagesWalkthrough/battle/imageswalkthroughgame_screen.dart

- Update gameplay for Images Walkthrough

Update 1v1 Gameplay

---

lib/api/room_api.dart
lib/models/notification_item.dart
lib/screens/game/room/create_room_screen.dart
lib/screens/game/room/waiting_lobby_screen.dart
lib/screens/notification/notiscreen.dart
lib/widgets/appbar/owner_appbar.dart
lib/widgets/appbar/room_appbar.dart
lib/widgets/others/noti_element.dart

- Update Appbar for screen
- Add function to cancel room party

Create Waiting Lobby Screen for Room Party

---

lib/api/room_api.dart
lib/data/data.dart
lib/models/account_in_room.dart
lib/models/room.dart
lib/screens/game/game_menu.dart
lib/screens/game/room/create_room_screen.dart
lib/screens/game/room/waiting_lobby_screen.dart
lib/widgets/appbar/owner_appbar.dart
lib/widgets/appbar/room_appbar.dart
lib/widgets/game/user_chip.dart

- Add API for enter and leave room function
- Add Join Room Function
- Add Leave Room Function for players in room
- Add User Chip display in Waiting Lobby Screen

Update Room Party Screen

---

lib/api/achieviements_api.dart
lib/api/authentication_api.dart
lib/api/battle_api.dart
lib/api/contest_api.dart
lib/helper/sharedpreferenceshelper.dart
lib/main.dart
lib/models/musicpassword.dart
lib/screens/contest/finalresult_screen.dart
lib/screens/game/battle_main_screen.dart
lib/screens/game/game_menu.dart
lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/screens/musicpassword/musicpass_battle_mainscreen.dart
lib/widgets/others/winscreen.dart

- Call save Result game battle api
- Add game mode battle for musicpassword

Game battle fuction

---

lib/api/analytics_api.dart
lib/screens/analytics/statistics_screen.dart
lib/screens/game/level_select.dart
lib/screens/home.dart
lib/screens/notification/notiscreen.dart
lib/screens/option_home.dart

- Fix when back from level screen to menu screen (Wrong navigator in Images Walkthrough)

Fix Game Level Screen

---

lib/api/battle_api.dart
lib/screens/contest/finalresult_screen.dart
lib/screens/game/battle_main_screen.dart
lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/screens/musicpassword/musicpass_battle_mainscreen.dart

- Fix chat not double
- Fix UI Musicpassword battle
- Fix Win_Screen

Fix game battle

---

lib/api/battle_api.dart

Fix Battle api

---

lib/api/contest_api.dart
lib/screens/account/editaccount_screen.dart
lib/screens/authentication/loginscreen.dart
lib/widgets/appbar/normal_appbar.dart

- Fix update profile when logging in with google
- Update TNormalAppbar

Fix Update Account Screen

---

lib/api/icon_api.dart
lib/helper/sharedpreferenceshelper.dart
lib/models/icon.dart
lib/screens/authentication/loginscreen.dart
lib/widgets/appbar/battle_game_appbar.dart

- Show Icon Chosen in Battle 1v1

Add Icon Chosen

---

lib/main.dart
lib/screens/authentication/registerscreen.dart

- When successfully registering account, navigate to Login Screen instead

Update Main Flow

---

lib/api/room_api.dart
lib/screens/game/game_menu.dart
lib/screens/game/room/create_room_screen.dart
lib/screens/game/room/waiting_lobby_screen.dart
lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/screens/musicpassword/musicpass_battle_mainscreen.dart
lib/widgets/appbar/battle_game_appbar.dart

- Add reatime wait in room
- Add information realtime in room

Add Realtime for Room mode

---

lib/api/assets_api.dart
lib/api/init_api.dart
lib/helper/sharedpreferenceshelper.dart
lib/models/findanounymous_assets.dart
lib/models/image_resource.dart
lib/models/musicpasssource.dart
lib/screens/contest/contest_menu.dart
lib/screens/game/game_menu.dart
lib/screens/startscreen.dart

- Add get Topic Id
- Save, add topic Id Shareprereference

Update API Resource, Shareprereferences Resource

---

lib/api/friends_api.dart
lib/api/room_api.dart
lib/helper/sharedpreferenceshelper.dart
lib/models/imageswalkthrough_game.dart
lib/screens/friend/addfriend_screen.dart
lib/screens/game/game_menu.dart
lib/screens/game/leaderboard.dart
lib/screens/game/room/create_room_screen.dart
lib/screens/game/room/waiting_lobby_screen.dart
lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/imagesWalkthrough/imageswalkthroughgame_screen.dart
lib/screens/imagesWalkthrough/startgame_screen.dart

- Update friend API
- Add new Room API
- Add get Resource by topic
- Show leader board when completed room mode

Update API, Room mode

---

lib/api/friends_api.dart
lib/screens/friend/addfriend_screen.dart
lib/screens/game/leaderboard.dart
lib/screens/game/room/waiting_lobby_screen.dart

- Enter flipcard in room mode
- Not accept with cancel friendship

Update addfriend function, roommode

---

lib/api/room_api.dart
lib/models/flipcard.dart
lib/models/imageswalkthrough_game.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/friend/challenge_player_screen.dart
lib/screens/game/battle_main_screen.dart
lib/screens/game/leaderboard.dart
lib/screens/game/room/waiting_lobby_screen.dart
lib/widgets/appbar/game_appbar.dart

- Fix bug roommode
- Add play with friend mode

Update roomMode, add Play with Friend mode

---

lib/api/battle_api.dart
lib/helper/sharedpreferenceshelper.dart
lib/main.dart
lib/screens/authentication/loginscreen.dart
lib/screens/contest/finalresult_screen.dart
lib/screens/friend/challenge_player_screen.dart
lib/screens/game/battle_main_screen.dart
lib/screens/musicpassword/musicpass_battle_mainscreen.dart
lib/screens/musicpassword/musicpassgame.dart
lib/screens/startscreen.dart

- 10 times to listen for muscipassword
- Call API enqueue when dispose find opponent
- Quit screen with contest
- Set online real_time
- Hidden Contest expired

Refactor Functions

---

lib/api/authentication_api.dart
lib/api/battle_api.dart
lib/api/firebase_message_api.dart
lib/api/room_api.dart
lib/main.dart
lib/screens/authentication/loginscreen.dart
lib/screens/contest/contest_menu.dart
lib/screens/contest/finalresult_screen.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/friend/challenge_player_screen.dart
lib/screens/game/battle_main_screen.dart
lib/screens/game/game_menu.dart
lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/screens/imagesWalkthrough/battle/imageswalkthroughgame_screen.dart
lib/screens/imagesWalkthrough/endgame_screen.dart
lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/imagesWalkthrough/imageswalkthroughgame_screen.dart
lib/screens/musicpassword/musicpass_battle_mainscreen.dart
lib/screens/musicpassword/musicpassgame.dart
lib/screens/startscreen.dart
lib/widgets/appbar/battle_game_appbar.dart
lib/widgets/game/level_item.dart
lib/widgets/others/noti_element.dart

- Add report message
- Handle quitgame room
- Fix continue at winscreen and result screen
- PushandremoveUntil at LevelScreen
- Handle coin enough to play
- Add set status islogin

Add and fix functions

---

lib/api/authentication_api.dart
lib/api/firebase_message_api.dart
lib/screens/authentication/loginscreen.dart
lib/screens/authentication/registerscreen.dart

- Add feature login concurrency
- Set online when logout

Add feature login concurrency

---

lib/controller/network_manager.dart

- Exit app automatically when reconnecting to local network.

Handle when network reconnecting

---

lib/api/analytics_api.dart
lib/api/room_api.dart
lib/models/analysis_group.dart
lib/models/analysis_group_average.dart
lib/models/flipcard.dart
lib/screens/analytics/scatter_chart_memory.dart
lib/screens/analytics/statistics_screen.dart
lib/screens/contest/instruction_screen.dart
pubspec.lock
pubspec.yaml

- Create function to get data of average score of players in each game
- Create chart to see memory improvement process through each game

Update Statistics Screen

---

lib/api/account_api.dart
lib/api/authentication_api.dart
lib/api/battle_api.dart
lib/api/challenges_api.dart
lib/api/contest_api.dart
lib/api/icon_api.dart
lib/screens/account/account_mainscreen.dart
lib/screens/achievement/challenges_screen.dart
lib/screens/authentication/loginscreen.dart
lib/screens/authentication/registerscreen.dart
lib/screens/contest/finalresult_screen.dart
lib/screens/findanonymous/findanonymous_game.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/game/game_menu.dart
lib/screens/game/room/waiting_lobby_screen.dart
lib/screens/imagesWalkthrough/battle/game_mainscreen.dart
lib/screens/imagesWalkthrough/game_mainscreen.dart
lib/screens/musicpassword/musicpass_battle_mainscreen.dart
lib/screens/musicpassword/musicpassgame.dart

- Update coin in GetAccountById
- Update coin in FinalResult Screen
- Update content popup
- Fix Progress Challenge

Update Popup and fix fucntion:

---

lib/screens/game/room/waiting_lobby_screen.dart

- Adding "Waiting for other player" in screen

Update UI of Waiting Room Screen

---

lib/api/battle_api.dart
lib/api/room_api.dart
lib/screens/flipcard/flipcard_game.dart
lib/screens/game/battle_main_screen.dart
lib/screens/game/room/waiting_lobby_screen.dart

- Remove 1v1Room
- Remove room
- Cancle listen realtime

Add remove realtimedatabase

---

lib/api/icon_api.dart
lib/screens/analytics/line_chart_memory.dart
lib/screens/authentication/loginscreen.dart
lib/screens/iconShop/icon_selection_screen.dart
lib/screens/iconShop/own_icon_screen.dart

- Pagination for list of icon in shop
- Increase value of vertical axis in chart to 3

Update Icon Shop Screen & Fix Line Chart of Level Cluster
